version: "3.7"

networks:
  iotaccess-network:

services:

  random-number-ws:
    build:
      context: ../random-number-ws
      args:
        RANDOM_NUMBER_WS_ARGS:
    image: random-number-ws-image
    container_name: random-number-ws
    ports:
      - "8081:8081"
      - "1045:1044"
    networks:
      - iotaccess-network