version: "3.7"

networks:
  iotaccess-network:

services:

  postgres12:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - iotaccess-network