version: "3.7"

networks:
  masterthesis-network:

services:

  core:
    build:
      context: ../core
      args:
        CORE_ARGS:
    image: core-image
    container_name: core
    ports:
      - "8080:8080"
      - "1044:1044"
    networks:
      - masterthesis-network
    depends_on:
      - postgres12
      - random-number-ws

  random-number-ws:
    build:
      context: ../random-number-ws
      args:
        RANDOM_NUMBER_WS_ARGS:
    image: random-number-ws-image
    container_name: random-number-ws
    ports:
      - "8081:8080"
      - "1045:1044"
    networks:
      - masterthesis-network

  postgres12:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - masterthesis-network