version: "3.7"

networks:
  iotaccess-network:

services:

  core:
    build:
      context: ../core
      args:
        CORE_ARGS:
    image: core-image
    container_name: core
    ports:
      - "8080:8080"
      - "1044:1044"
    networks:
      - iotaccess-network
    depends_on:
      - postgres12

  postgres12:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - iotaccess-network