version: "3.7"

networks:
  iotaccess-network:

services:

  core:
    build:
      context: ../core
      args:
        CORE_ARGS:
    image: core-image
    container_name: core
    ports:
      - "8080:8080"
      - "1044:1044"
    networks:
      - iotaccess-network